### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
Hi [guibranco](https://github.com/guibranco),
just trying to fix issue #52, please check it out

### CODE REVIEW

**Comment by guibranco** [comment]
@viktoriussuwandi thanks for the PR, I just need to figure out how to allow forks to execute the pipeline. I will try it later!
Thanks again.

**Comment by guibranco** [comment]
WIP for the pipeline fix. Ref: guilhermestracini/apiclient-boilerplate-dotnet#90

**Comment by viktoriussuwandi** [comment]
> WIP for the pipeline fix. Ref: [GuilhermeStracini/apiclient-boilerplate-dotnet#90](https://github.com/GuilhermeStracini/apiclient-boilerplate-dotnet/issues/90)

Hi @guibranco,
Is there anything else need to do to merge this PR 
(also another my PRs on another your projects),

or should it close without merge ?
Please let me know

**Comment by guibranco** [comment]
@viktoriussuwandi I am working on it, as soon as I fixed the problems in the pipeline and actions I will merge it in all repositories.

**Comment by viktoriussuwandi** [comment]
Thanks @guibranco !

**Pull request merged**
